language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-auth-microservice project/auth-api/
  - docker tag udagram-auth-microservice thedemon12/udagram-auth-microservice:latest
  - docker build -t udagram-feed-microservice project/feed-api/
  - docker tag udagram-feed-microservice thedemon12/udagram-feed-microservice:latest
  - docker build -t udagram-reverse-proxy project/reverse-proxy/
  - docker tag udagram-reverse-proxy thedemon12/udagram-reverse-proxy:latest

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push thedemon12/udagram-auth-microservice
  - docker push thedemon12/udagram-feed-microservice
  - docker push thedemon12/udagram-reverse-proxy
